/* Generated by gen_iir_coef.m. Fs=2.6e+07 Hz, band=100000..1e+06 Hz. */
#ifndef PD_IIR_COEF_FS26M_H
#define PD_IIR_COEF_FS26M_H
static const unsigned int pd_iir_coef_fs26m[5] = { 0x01916, 0x00000, 0x3E6EA, 0x23385, 0x0CDD4 };
#endif
