/* Generated by gen_iir_coef.m. Fs=6.5e+07 Hz, band=100000..1e+06 Hz. */
#ifndef PD_IIR_COEF_FS65M_H
#define PD_IIR_COEF_FS65M_H
static const unsigned int pd_iir_coef_fs65m[5] = { 0x00AAC, 0x00000, 0x3F554, 0x21592, 0x0EAA9 };
#endif
