/* Generated by gen_iir_coef.m. Fs=1.625e+07 Hz, band=100000..1e+06 Hz. */
#ifndef PD_IIR_COEF_FS16P25M_H
#define PD_IIR_COEF_FS16P25M_H
static const unsigned int pd_iir_coef_fs16p25m[5] = { 0x025DC, 0x00000, 0x3DA24, 0x24EFB, 0x0B447 };
#endif
