% Generate and validate one RBJ band-pass section for pd_filter_chain.
% Usage: run this file from MATLAB with the project sim directory as cwd.
% The RTL uses Q1.16 coefficients stored in the low 18 AXI bits.

clear; clc;

FsList = [26e6, 16.25e6, 65e6];
fLow = 100e3;
fHigh = 1e6;
f0 = sqrt(fLow*fHigh);
outDir = fileparts(mfilename('fullpath'));

for k = 1:numel(FsList)
    Fs = FsList(k);
    tag = fs_tag(Fs);
    w0 = 2*pi*f0/Fs;
    Q = f0/(fHigh-fLow);
    alpha = sin(w0)/(2*Q);
    den = 1 + alpha;
    b = [alpha/den, 0, -alpha/den];
    a = [1, -2*cos(w0)/den, (1-alpha)/den];

    q = round([b, a(2:3)] * 2^16);
    assert(all(q >= -131072 & q <= 131071), 'Coefficient clamp at Fs=%g', Fs);
    poles = roots(a);
    assert(all(abs(poles) < 1), 'Unstable coefficient set at Fs=%g', Fs);

    q18 = mod(q, 2^18);
    float_rows = [(1:5).', [b(:); a(2:3).']];
    writematrix(float_rows, fullfile(outDir, ['coef_' tag '_float.csv'])); %#ok<WRM>
    writematrix([q(:), q18(:)], fullfile(outDir, ['coef_' tag '_q16.csv'])); %#ok<WRM>

    fid = fopen(fullfile(outDir, ['coef_' tag '.hex']), 'w');
    assert(fid >= 0, 'Cannot open coefficient hex output');
    fprintf(fid, '%05X\n', q18);
    fclose(fid);

    fid = fopen(fullfile(outDir, ['coef_' tag '.h']), 'w');
    assert(fid >= 0, 'Cannot open coefficient header output');
    fprintf(fid, '/* Generated by gen_iir_coef.m. Fs=%g Hz, band=%g..%g Hz. */\n', Fs, fLow, fHigh);
    fprintf(fid, '#ifndef PD_IIR_COEF_%s_H\n#define PD_IIR_COEF_%s_H\n', upper(tag), upper(tag));
    fprintf(fid, 'static const unsigned int pd_iir_coef_%s[5] = { ', tag);
    fprintf(fid, '0x%05X, ', q18(1:4)); fprintf(fid, '0x%05X };\n', q18(5));
    fprintf(fid, '#endif\n');
    fclose(fid);

    f = logspace(log10(max(50, fLow/100)), log10(min(Fs/2*0.999, fHigh*20)), 2000);
    z = exp(1j*2*pi*f/Fs);
    H = (b(1) + b(2)./z + b(3)./z.^2) ./ (a(1) + a(2)./z + a(3)./z.^2);
    fid = fopen(fullfile(outDir, ['resp_' tag '.csv']), 'w');
    fprintf(fid, 'frequency_hz,gain_db\n');
    fprintf(fid, '%.9g,%.9f\n', [f; 20*log10(max(abs(H), realmin))]);
    fclose(fid);

    fprintf('Fs=%g: q=[%d %d %d %d %d], pole_radius=[%.9f %.9f]\n', ...
        Fs, q, abs(poles(1)), abs(poles(2)));
end

function tag = fs_tag(Fs)
    if abs(Fs-26e6) < 1, tag = 'fs26m';
    elseif abs(Fs-16.25e6) < 1, tag = 'fs16p25m';
    elseif abs(Fs-65e6) < 1, tag = 'fs65m';
    else, tag = strrep(sprintf('fs_%g', Fs), '.', 'p');
    end
end
