`timescale 1ns / 1ps
// =============================================================================
// pd_dds_adc_source.v -- continuous four-channel 65 MSPS PD test source
// -----------------------------------------------------------------------------
// Each channel reads a 1024 x 12-bit signed Q1.11 pulse template from a
// COE-initialized Block Memory Generator ROM. A compact MATLAB-derived event
// schedule repeats every 20 ms; the ROM streams one sample per ADC clock and
// therefore does not store/replay a 40 ms acquisition record.
//
// adc_data remains four synchronized 12-bit ADC codes packed as
// {CH3[11:0], CH2[11:0], CH1[11:0], CH0[11:0]}. adc_dv is asserted for every
// sample after the one-cycle ROM warm-up. This is a synthetic board-test
// stimulus, not a substitute for the physical ADC interface or measured data.
// =============================================================================
module pd_dds_adc_source #(
    parameter integer CLK_HZ          = 65000000,
    parameter integer SAMPLE_HZ       = 65000000,
    parameter integer SYNC_HZ         = 50,
    parameter integer ADC_W           = 12,
    parameter integer NUM_CH          = 4
)(
    input  wire                     clk,
    input  wire                     rst_n,
    output reg  [NUM_CH*ADC_W-1:0]  adc_data,
    output reg  [NUM_CH-1:0]        adc_dv,
    output reg                      sync_in
);

    localparam integer CLK_PER_SAMPLE = CLK_HZ / SAMPLE_HZ;
    localparam integer SYNC_SAMPLES   = SAMPLE_HZ / SYNC_HZ;
    localparam integer TEMPLATE_LEN   = 1024;
    localparam [20:0] LAST_SAMPLE     = SYNC_SAMPLES - 1;

    reg [2:0] tick_div;
    reg [20:0] cycle_sample;
    reg [20:0] rom_sample_tag;
    reg        rom_sample_valid;
    reg        rom_event_active0, rom_event_active1;
    reg        rom_event_active2, rom_event_active3;
    reg [9:0]  rom_event_addr0, rom_event_addr1;
    reg [9:0]  rom_event_addr2, rom_event_addr3;
    reg signed [11:0] rom_event_amp0, rom_event_amp1;
    reg signed [11:0] rom_event_amp2, rom_event_amp3;
    reg [15:0] phase0, phase1, phase2, phase3;
    reg [15:0] rom_phase0, rom_phase1, rom_phase2, rom_phase3;

    wire sample_ce = (tick_div == CLK_PER_SAMPLE - 1);

    wire        schedule_active0, schedule_active1;
    wire        schedule_active2, schedule_active3;
    wire [9:0]  schedule_addr0, schedule_addr1;
    wire [9:0]  schedule_addr2, schedule_addr3;
    wire signed [11:0] schedule_amp0, schedule_amp1;
    wire signed [11:0] schedule_amp2, schedule_amp3;

    wire [11:0] template_q0, template_q1, template_q2, template_q3;
    wire [9:0] rom_addr0 = schedule_active0 ? schedule_addr0 : 10'd0;
    wire [9:0] rom_addr1 = schedule_active1 ? schedule_addr1 : 10'd0;
    wire [9:0] rom_addr2 = schedule_active2 ? schedule_addr2 : 10'd0;
    wire [9:0] rom_addr3 = schedule_active3 ? schedule_addr3 : 10'd0;

    // The schedule module is generated by the MATLAB stimulus generator from
    // pd_event_truth_physical_65m.csv. One 1024-sample pulse port per channel.
    pd_pd_event_schedule #(.CHANNEL(0), .TEMPLATE_LEN(TEMPLATE_LEN)) schedule_ch0 (
        .clk(clk), .rst_n(rst_n), .sample_ce(sample_ce),
        .sample_index(cycle_sample), .active(schedule_active0),
        .template_addr(schedule_addr0), .amplitude(schedule_amp0)
    );
    pd_pd_event_schedule #(.CHANNEL(1), .TEMPLATE_LEN(TEMPLATE_LEN)) schedule_ch1 (
        .clk(clk), .rst_n(rst_n), .sample_ce(sample_ce),
        .sample_index(cycle_sample), .active(schedule_active1),
        .template_addr(schedule_addr1), .amplitude(schedule_amp1)
    );
    pd_pd_event_schedule #(.CHANNEL(2), .TEMPLATE_LEN(TEMPLATE_LEN)) schedule_ch2 (
        .clk(clk), .rst_n(rst_n), .sample_ce(sample_ce),
        .sample_index(cycle_sample), .active(schedule_active2),
        .template_addr(schedule_addr2), .amplitude(schedule_amp2)
    );
    pd_pd_event_schedule #(.CHANNEL(3), .TEMPLATE_LEN(TEMPLATE_LEN)) schedule_ch3 (
        .clk(clk), .rst_n(rst_n), .sample_ce(sample_ce),
        .sample_index(cycle_sample), .active(schedule_active3),
        .template_addr(schedule_addr3), .amplitude(schedule_amp3)
    );

    // Generated by scripts/13_configure_matlab_coe_roms.tcl from the four
    // 12-bit COE files in sim/coe_templates. The ROM output is synchronous.
    pd_pd_template_rom_ch0 pulse_rom_ch0 (
        .clka(clk), .addra(rom_addr0), .douta(template_q0)
    );
    pd_pd_template_rom_ch1 pulse_rom_ch1 (
        .clka(clk), .addra(rom_addr1), .douta(template_q1)
    );
    pd_pd_template_rom_ch2 pulse_rom_ch2 (
        .clka(clk), .addra(rom_addr2), .douta(template_q2)
    );
    pd_pd_template_rom_ch3 pulse_rom_ch3 (
        .clka(clk), .addra(rom_addr3), .douta(template_q3)
    );

    wire signed [23:0] scaled_delta0 =
        ($signed(template_q0) * $signed(rom_event_amp0)) >>> 11;
    wire signed [23:0] scaled_delta1 =
        ($signed(template_q1) * $signed(rom_event_amp1)) >>> 11;
    wire signed [23:0] scaled_delta2 =
        ($signed(template_q2) * $signed(rom_event_amp2)) >>> 11;
    wire signed [23:0] scaled_delta3 =
        ($signed(template_q3) * $signed(rom_event_amp3)) >>> 11;

    function integer tri_wave;
        input [7:0] phase;
        integer magnitude;
        begin
            magnitude = phase[7] ? (127 - phase[6:0]) : phase[6:0];
            tri_wave = magnitude - 64;
        end
    endfunction

    function [11:0] saturate_u12;
        input integer sample;
        begin
            if (sample < 0)
                saturate_u12 = 12'd0;
            else if (sample > 4095)
                saturate_u12 = 12'hFFF;
            else
                saturate_u12 = sample[11:0];
        end
    endfunction

    wire [11:0] ch0_sample = saturate_u12(2048 +
        (tri_wave(rom_phase0[15:8]) >>> 2) +
        ((rom_sample_valid && rom_event_active0) ? scaled_delta0 : 0));
    wire [11:0] ch1_sample = saturate_u12(2056 +
        (tri_wave(rom_phase1[15:8]) >>> 2) +
        ((rom_sample_valid && rom_event_active1) ? scaled_delta1 : 0));
    wire [11:0] ch2_sample = saturate_u12(2038 +
        (tri_wave(rom_phase2[15:8]) >>> 1) +
        ((rom_sample_valid && rom_event_active2) ? scaled_delta2 : 0));
    wire [11:0] ch3_sample = saturate_u12(2062 +
        (tri_wave(rom_phase3[15:8]) >>> 2) +
        ((rom_sample_valid && rom_event_active3) ? scaled_delta3 : 0));

`ifndef SYNTHESIS
    initial begin
        if ((CLK_PER_SAMPLE != 1) || (CLK_PER_SAMPLE * SAMPLE_HZ != CLK_HZ))
            $error("pd_dds_adc_source requires a 65 MHz clock and 65 MSPS sample rate");
        if ((SYNC_SAMPLES != 1300000) || (SYNC_SAMPLES * SYNC_HZ != SAMPLE_HZ))
            $error("pd_dds_adc_source requires a 50 Hz / 65 MSPS integer ratio");
        if ((ADC_W != 12) || (NUM_CH != 4))
            $error("pd_dds_adc_source packs four 12-bit channels");
    end
`endif

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            tick_div         <= 3'd0;
            cycle_sample     <= 21'd0;
            rom_sample_tag   <= 21'd0;
            rom_sample_valid <= 1'b0;
            rom_event_active0 <= 1'b0;
            rom_event_active1 <= 1'b0;
            rom_event_active2 <= 1'b0;
            rom_event_active3 <= 1'b0;
            rom_event_addr0   <= 10'd0;
            rom_event_addr1   <= 10'd0;
            rom_event_addr2   <= 10'd0;
            rom_event_addr3   <= 10'd0;
            rom_event_amp0    <= 12'sd0;
            rom_event_amp1    <= 12'sd0;
            rom_event_amp2    <= 12'sd0;
            rom_event_amp3    <= 12'sd0;
            phase0           <= 16'd0;
            phase1           <= 16'd13568;
            phase2           <= 16'd27392;
            phase3           <= 16'd45824;
            rom_phase0       <= 16'd0;
            rom_phase1       <= 16'd13568;
            rom_phase2       <= 16'd27392;
            rom_phase3       <= 16'd45824;
            adc_data         <= {4{12'd2048}};
            adc_dv           <= {NUM_CH{1'b0}};
            sync_in          <= 1'b0;
        end else if (sample_ce) begin
            tick_div <= 3'd0;

            if (rom_sample_valid) begin
                adc_data <= {ch3_sample, ch2_sample, ch1_sample, ch0_sample};
                adc_dv   <= {NUM_CH{1'b1}};
                sync_in  <= (rom_sample_tag == 21'd0);
            end else begin
                adc_data <= {4{12'd2048}};
                adc_dv   <= {NUM_CH{1'b0}};
                sync_in  <= 1'b0;
            end

            rom_sample_tag   <= cycle_sample;
            rom_sample_valid <= 1'b1;
            rom_event_active0 <= schedule_active0;
            rom_event_active1 <= schedule_active1;
            rom_event_active2 <= schedule_active2;
            rom_event_active3 <= schedule_active3;
            rom_event_addr0   <= schedule_addr0;
            rom_event_addr1   <= schedule_addr1;
            rom_event_addr2   <= schedule_addr2;
            rom_event_addr3   <= schedule_addr3;
            rom_event_amp0    <= schedule_amp0;
            rom_event_amp1    <= schedule_amp1;
            rom_event_amp2    <= schedule_amp2;
            rom_event_amp3    <= schedule_amp3;
            rom_phase0       <= phase0;
            rom_phase1       <= phase1;
            rom_phase2       <= phase2;
            rom_phase3       <= phase3;

            // Retain the existing low-level synthetic background frequencies.
            phase0 <= phase0 + 16'd307;
            phase1 <= phase1 + 16'd512;
            phase2 <= phase2 + 16'd717;
            phase3 <= phase3 + 16'd1126;

            if (cycle_sample == LAST_SAMPLE)
                cycle_sample <= 21'd0;
            else
                cycle_sample <= cycle_sample + 21'd1;
        end else begin
            tick_div <= tick_div + 3'd1;
        end
    end
endmodule
