`timescale 1ns / 1ps
// =============================================================================
// pd_dds_adc_source.v -- synthesizable on-chip four-channel ADC test source
// -----------------------------------------------------------------------------
// Board-test mode only. The source runs from the internally generated 26 MHz
// ADC clock and emits one valid sample on every clock edge.
// It emits four low-amplitude background waveforms plus one 32-sample PD
// template per channel in every 20 ms (50 Hz) mains cycle. The templates
// below are exact ADC-code excerpts from sim/pd_adc_4ch_26m_40ms.mem,
// generated by sim/generate_pd_adc_waveform.m. They are synthetic laboratory
// stimuli, not field-measured partial-discharge records.
//
// This verifies: DDS source -> 26 MHz to 130 MHz CDC -> pd_ddr/pd_feature
// -> AXIS. It deliberately does not verify physical ADC pins or I/O timing.
// =============================================================================
module pd_dds_adc_source #(
    parameter integer CLK_HZ          = 26000000,
    parameter integer SAMPLE_HZ       = 26000000,
    parameter integer SYNC_HZ         = 50,
    parameter integer ADC_W           = 12,
    parameter integer NUM_CH          = 4
)(
    input  wire                     clk,
    input  wire                     rst_n,
    output reg  [NUM_CH*ADC_W-1:0]  adc_data,
    output reg  [NUM_CH-1:0]        adc_dv,
    output reg                      sync_in
);

    localparam integer CLK_PER_SAMPLE = CLK_HZ / SAMPLE_HZ;
    localparam integer SYNC_SAMPLES   = SAMPLE_HZ / SYNC_HZ;

    // In board-test mode CLK_HZ and SAMPLE_HZ are both 26 MHz.
    reg [2:0]  tick_div;
    reg [18:0] cycle_sample;
    reg [7:0]  phase0, phase1, phase2, phase3;

    function integer tri_wave;
        input [7:0] phase;
        integer magnitude;
        begin
            magnitude = phase[7] ? (127 - phase[6:0]) : phase[6:0];
            tri_wave = magnitude - 64;
        end
    endfunction

    // Index 0 is stored in bits [11:0]. Four 32x12-bit constant ROMs total
    // 1536 bits, versus 49,920,000 bits for the full 40 ms MATLAB file.
    localparam [383:0] MATLAB_CH0 = 384'h85384F85485284084884D82E83C83A82683082382783082D83E83B84785084D9A985269B849AA983A52E842C6A82A835;
    localparam [383:0] MATLAB_CH1 = 384'h86686D86E86B87B86D86E87386F86A86A86085F8508538AC84F7D38569068597598569D986767386FB2687949186C865;
    localparam [383:0] MATLAB_CH2 = 384'h77D77977577677C77878778B79879D79D79D79479B78E78D78678578278E77777D77676C77977F78280A78C6AF7948FD;
    localparam [383:0] MATLAB_CH3 = 384'h8AC7C774280D8FD7FA6B782A9BA7FB63883CA687F67B282888F80477381A8B67EE7278178F27ED6DE82C97BAC366B764;

    function [11:0] matlab_code;
        input [1:0] channel;
        input [4:0] index;
        begin
            case (channel)
                2'd0: matlab_code = MATLAB_CH0[index*12 +: 12];
                2'd1: matlab_code = MATLAB_CH1[index*12 +: 12];
                2'd2: matlab_code = MATLAB_CH2[index*12 +: 12];
                default: matlab_code = MATLAB_CH3[index*12 +: 12];
            endcase
        end
    endfunction

    function [11:0] saturate_u12;
        input integer sample;
        begin
            if (sample < 0)
                saturate_u12 = 12'd0;
            else if (sample > 4095)
                saturate_u12 = 12'hFFF;
            else
                saturate_u12 = sample[11:0];
        end
    endfunction

    wire sample_ce = (tick_div == CLK_PER_SAMPLE - 1);
    // Template index 2 contains the main excursion. Nominal centres are
    // 45/135/225/315 degrees of the 520000-sample mains cycle.
    wire [11:0] ch0_next = (cycle_sample >= 19'd64998 && cycle_sample < 19'd65030) ?
                          matlab_code(2'd0, cycle_sample - 19'd64998) :
                          saturate_u12(2048 + (tri_wave(phase0) >>> 2));
    wire [11:0] ch1_next = (cycle_sample >= 19'd194998 && cycle_sample < 19'd195030) ?
                          matlab_code(2'd1, cycle_sample - 19'd194998) :
                          saturate_u12(2056 + (tri_wave(phase1) >>> 2));
    wire [11:0] ch2_next = (cycle_sample >= 19'd324998 && cycle_sample < 19'd325030) ?
                          matlab_code(2'd2, cycle_sample - 19'd324998) :
                          saturate_u12(2038 + (tri_wave(phase2) >>> 1));
    wire [11:0] ch3_next = (cycle_sample >= 19'd454998 && cycle_sample < 19'd455030) ?
                          matlab_code(2'd3, cycle_sample - 19'd454998) :
                          saturate_u12(2062 + (tri_wave(phase3) >>> 2));

    initial begin
        if ((CLK_PER_SAMPLE != 1) || (CLK_PER_SAMPLE * SAMPLE_HZ != CLK_HZ))
            $error("pd_dds_adc_source requires a 26 MHz DDS clock and 26 MSPS sample rate");
        if ((SYNC_SAMPLES != 520000) || (SYNC_SAMPLES * SYNC_HZ != SAMPLE_HZ))
            $error("pd_dds_adc_source requires a 50 Hz / 26 MSPS integer ratio");
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            tick_div    <= 3'd0;
            cycle_sample <= 19'd0;
            phase0      <= 8'd0;
            phase1      <= 8'd53;
            phase2      <= 8'd107;
            phase3      <= 8'd179;
            adc_data    <= {NUM_CH{12'd2048}};
            adc_dv      <= {NUM_CH{1'b0}};
            sync_in     <= 1'b0;
        end else begin
            adc_dv  <= {NUM_CH{1'b0}};
            sync_in <= 1'b0;
            if (sample_ce) begin
                tick_div <= 3'd0;
                adc_data <= {ch3_next, ch2_next, ch1_next, ch0_next};
                adc_dv   <= {NUM_CH{1'b1}};
                sync_in  <= (cycle_sample == 19'd0);

                phase0 <= phase0 + 8'd3;
                phase1 <= phase1 + 8'd5;
                phase2 <= phase2 + 8'd7;
                phase3 <= phase3 + 8'd11;
                if (cycle_sample == SYNC_SAMPLES - 1)
                    cycle_sample <= 19'd0;
                else
                    cycle_sample <= cycle_sample + 19'd1;
            end else begin
                tick_div <= tick_div + 3'd1;
            end
        end
    end
endmodule
